Models/Animal.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Assessment7.Models
{

    public class Animal
    {
       
        public AnimalResult[] results { get; set; }
        
    }

    public class AnimalResult
    {
        public string Name { get; set; }
        public float Weight { get; set; }
        public SpeciesName Species { get; set; }
    }

    public class SpeciesName
    {
        public string Name { get; set; }
    }
}

Models/Donut.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Assessment7.Models
{
    public class Donut
    {
        public int id { get; set; }
        public string name { get; set; }
        public int calories { get; set; }
        public string[] extras { get; set; }
        public string photo { get; set; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace Assessment7.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Location.cs
using Newtonsoft.Json;
using System.Text.Json.Serialization;

namespace Assessment7.Models
{
    //public class GeoCode
    //{
    //    public Result[] results { get; set; }
    //}

    //public class Result
    //{
    //    public string formatted_address { get; set; }
    //    public Geometry geometry { get; set; }
    //}

    //public class Geometry
    //{
    //    public Location location { get; set; }
    //}

    public class Location
    {
        [JsonProperty(PropertyName = "lat")]
        public float Latitude { get; set; }

        [JsonProperty(PropertyName = "lng")]
        public float Longitude { get; set; }
    }
}

Models/Places.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Assessment7.Models
{

    public class PlacesResponse
    {
        public object[] html_attributions { get; set; }
        public string next_page_token { get; set; }
        public Place[] results { get; set; }
        public string status { get; set; }
    }

    public class Place
    {
        public string business_status { get; set; }
        public Geometry geometry { get; set; }
        public string icon { get; set; }
        public string name { get; set; }
        public Opening_Hours opening_hours { get; set; }
        public Photo[] photos { get; set; }
        public string place_id { get; set; }
        public Plus_Code plus_code { get; set; }
        public float rating { get; set; }
        public string reference { get; set; }
        public string scope { get; set; }
        public string[] types { get; set; }
        public int user_ratings_total { get; set; }
        public string vicinity { get; set; }
        public bool permanently_closed { get; set; }
    }

    public class Geometry
    {
        public Location location { get; set; }
    }

    public class Opening_Hours
    {
        public bool open_now { get; set; }
    }

    public class Plus_Code
    {
        public string compound_code { get; set; }
        public string global_code { get; set; }
    }

    public class Photo
    {
        public int height { get; set; }
        public string[] html_attributions { get; set; }
        public string photo_reference { get; set; }
        public int width { get; set; }
    }
}

Models/Species.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Assessment7.Models
{

    public class Species
    {
        public string name { get; set; }
      
        public string diet { get; set; }

        public string habitat { get; set; }
    }

}

Controllers/HomeController.cs
 using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Assessment7.Models;
using Assessment7.Services;

namespace Assessment7.Controllers
{
    public class HomeController : Controller
    {
        private readonly IAnimalService _service;
        private readonly ILocationService _locationService;

        public HomeController(IAnimalService service, ILocationService locationService)
        {
            _service = service;
            _locationService = locationService;
        }

        public async Task<IActionResult> Index()
        {
            Animal zoo = await _service.GetAsync<Animal>("https://gc-zoo.surge.sh/api/animals.json");

            //var zoo = await _service.GetAllAnimals();
            return View(zoo.results);
        }


        public IActionResult Privacy()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Species(string SpeciesName)
        {
            string baseUrl = "https://gc-zoo.surge.sh";
            string endpoint = $"/api/species/{SpeciesName}.json";
            Species animal = await _service.GetAsync<Species>(baseUrl + endpoint);

            //var animal = await _service.GetAnAnimal(SpeciesName);
            return View(animal);
        }

        public async Task<IActionResult> GetDonuts(string id)
        {
            var donutBaseUrl = "https://grandcircusco.github.io/demo-apis/";
            var donutEndPoint = $"donuts/{id}.json";
            Donut donut = await _service.GetAsync<Donut>(donutBaseUrl + donutEndPoint);

            return View(donut);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/PlacesController.cs
using Assessment7.Services;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Assessment7.Controllers
{
    public class PlacesController : Controller
    {
        private readonly ILocationService _locationService;

        public PlacesController(ILocationService locationService)
        {
            _locationService = locationService;
        }

        public IActionResult Index()
        {
            return View();
        }


        public async Task<IActionResult> GetPlaces(string address, int radius, string type)
        {
            var location = await _locationService.GetLocationAsync(address);

            var places = await _locationService.GetPlacesAsync(location, radius, type);
            ViewData["type"] = type;
            return View(places);
        }
    }
}

Views/Home/GetDonuts.cshtml
@model Assessment7.Models.Donut

@{
    ViewData["Title"] = "GetDonuts";
}

<h1>GetDonuts</h1>

<div>
    <h4>Donut</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.calories)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.calories)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.photo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.photo)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

Views/Home/GetLongLat.cshtml
@model Assessment7.Models.Location

@{
    ViewData["Title"] = "GetLongLat";
}

<h1>GetLongLat</h1>

<div>
    <h4>LongLatFinder</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Latitude)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Latitude)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Longitude)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Longitude)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

Views/Home/Index.cshtml
@model IEnumerable<Assessment7.Models.AnimalResult>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<table class="table">
    <thead>
        <tr>

            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Weight)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>

                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Weight)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Species.Name)
                </td>

            </tr>
        }
    </tbody>
</table>
<form asp-controller="Home" asp-action="Species">
    SpeciesName: <input type="text" name="SpeciesName" />
    <input type="submit" value="Search" class="btn btn-dark" />
</form>
<h2>Press Play if you want to have a fun moment before you search</h2>
<iframe width="900" height="520" src="https://www.youtube.com/embed/YbIPizloGdg" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

Views/Home/Species.cshtml
@model Assessment7.Models.Species

@{
    ViewData["Title"] = "Species";
}

<h1>Species</h1>

<div>
    <h4>Species</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.diet)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.diet)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.habitat)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.habitat)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

Views/Places/GetPlaces.cshtml
@model IEnumerable<Place>

@{
    ViewData["Title"] = "GetPlaces";
}

<h1>Display Places</h1>

<div class="col-md-12">

    @*//table table-bordered table-responsive table-striped*@
    <table class=" table-bordered table-dark table-hover table-striped">
        <thead>
            <tr>
                <th scope="col"></th>
                <th scope="col">Name</th>
                <th scope="col">Rating</th>
                <th scope="col">Type</th>

            </tr>
        </thead>
        <tbody>

            @foreach (var place in Model)
            {
                <tr>
                    <th scope="row"></th>
                    <td>@place.name</td>
                    <td>@place.rating</td>
                    <td>@ViewData["type"]</td>

                </tr>
            }
        </tbody>
    </table>

</div>

Views/Places/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<form asp-action="GetPlaces">
    Address/Zip <input type="text" name="address" /> <br />
   Radius<select name="radius">
        <option value="5000">5km</option>
        <option value="10000">10km</option>
        <option value="15000">15km</option>
        <option value="20000">20km</option>
    </select><br />
    Activities<select name="type">
        <option value="gym">Gym</option>
        <option value="cafe">Coffee Shops</option>
        <option value="yoga">Yoga</option>
        <option value="restaurants">Restaurants</option>
        <option value="market">Markets</option>
        <option value="hotels">Hotels</option>
    </select>

    <input type="submit" value="Search"/>
</form>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Assessment7</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Assessment7</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Places" asp-action="Index">Locations</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Assessment7 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>